foreground #fcfcfc
background #31363b

color0 #232627   # 黑
color1 #ed1515   # 红
color2 #11d116   # 绿
color3 #f67400   # 黄
color4 #1d99f3   # 蓝
color5 #9b59b6   # 紫
color6 #1abc9c   # 青
color7 #fcfcfc   # 白

color8  #7f8c8d  # 亮黑
color9  #c0392b  # 亮红
color10 #1cdc9a  # 亮绿
color11 #fdbc4b  # 亮黄
color12 #3daee9  # 亮蓝
color13 #8e44ad  # 亮紫
color14 #16a085  # 亮青
color15 #ffffff  # 亮白

dim_opacity 0.75

cursor none
